### ISSUE TITLE
error in put vertical buying power calculation

### ISSUE THREAD

**Issue by bayareacoder** [sirnfs/OptionSuite#14]
I believe the buying power (margin) requirement for a short vertical in `putVertical.py`, shown as:
      ```buyingPower = ((self.__putToSell.strikePrice - self.__putToBuy.strikePrice) - (
      currentPutToSellPrice - currentPutToBuyPrice)) * self.__numContracts * 100```

is not correct. It should be just the width of the spread * 100 * number of contracts as that is the max value it could achieve if the short spread is fully in the money. So:
      ```buyingPower = (self.__putToSell.strikePrice - self.__putToBuy.strikePrice) * self.__numContracts * 100```

UPDATE: OK I guess they allow the credit received to count against the margin requirement. That could be specific to Tastytrade. Then it's correct.
https://support.tastytrade.com/support/s/solutions/articles/43000435260

**Comment by sirnfs** [comment]
I believe this is correct. Can you please check the explanation and example
here: https://tastytrade.com/learn/options/short-put-vertical-spread/

**Comment by bayareacoder** [comment]
Yes it is correct as mentioned in my update. But when you do iron condors (vertical put & call spread) then it's not so simple as now the margin requirement of a put vertical depends on matching call verticals in the portfolio. 
Have you done code for an iron condor (i.e. matching put + call short verticals) strategy?

**Comment by sirnfs** [comment]
I don't have code for an iron condor, but here's how the buying power is
calculated with Tastytrade:
https://support.tastytrade.com/support/s/solutions/articles/43000435229

**Comment by sirnfs** [comment]
Note that I actually checked and and confirmed this on the Tastytrade
platform.

**Comment by sirnfs** [comment]
Going to go ahead and close this issue. Thanks for reviewing the code.
