### ISSUE TITLE
Using Backtester.py for put options

### ISSUE THREAD

**Issue by dw-coder** [sirnfs/OptionSuite#4]
Michael,
Great program!
My question is how should you change the strangle strategy to just perform a put strategy? I am new to backtesting with options and I could not quite follow how to use the program with different strategies.  I am interested in developing a protective put strategy with a covered call strategy, but with different delta, ivolatilities, etc.  So, I can run two separate models and then combine the results.

**Comment by sirnfs** [comment]
You need to use the Strategy abstract class found in OptionSuite/strategyManager/strategy.py. There is an example in OptionSuite/strategyManager/StrangleStrat.py for the strangle strategy.
