### ISSUE TITLE
Detection of monthly option in case of a holiday

### ISSUE THREAD

**Issue by bayareacoder** [sirnfs/OptionSuite#5]
Great library!

I don't think the detection of a monthly option is 100% correct, as the implementation is different than the doc string (which is correct).

In file `StrangleStrat.py`:
```
    def isMonthlyExp(self, dateTime):
        """
        Check if the option expiration falls on the third Friday of the month, or 
        if the third Friday is a holiday, check if the expiration falls on the Thursday that precedes it.
        :param dateTime: option expiration date in mm/dd/yy format.
        :return: True if it's a monthly option; False otherwise.
        """
        return (dateTime.weekday() == 4 and 14 < dateTime.day < 22)
```
The implementation identifies a Monthly expiration as a Friday in the 3rd week. So it actually won't detect if that day would be a holiday and the expiration is moved back 1 business day, which is what would happen if the 3rd Fri was a holiday per the CBOE website at least for SPX options: (https://www.cboe.com/tradable_products/sp_500/spx_options/):
"In the case of a holiday on the settlement date, the settlement date is **moved back one business day (e.g. from Friday to Thursday)**, with the exception of Monday Weeklys, where the settlement date will move forward one business day (i.e. Monday to Tuesday). In addition, no SPX EOW, Wednesday Weeklys, or Monday Weeklys will be listed that would have an expiration date that coincides with the expiration date of a traditional SPX option or SPX EOM option."

So since a Wed Weekly would move back to Tues if Wed is a holiday (it wouldn't move to Thurs), and no Weekly can have a same expiration as a Monthly, and an EOM cannot expire in the 3rd week, it seems to me it's safe to detect a Thurs expiration in the 3rd week ALSO as a Monthly expiration, and thus OR that to the above condition in the function.

Or just use the SPXW (vs SPX) option symbol identifier in the iVolatility data to identify the Weeklys...

**Comment by sirnfs** [comment]
Thanks for the feedback. Only monthly expirations are supported at the moment. Happy to take new contributions / PRs.
