### ISSUE TITLE
DTE vs expiration date

### ISSUE THREAD

**Issue by bayareacoder** [sirnfs/OptionSuite#6]
There seems to be a mixup between DTE (days to expiration) and expiration date that can lead to confusion.

In file `option.py` in `base` folder, there is a method to calculate the # of days left to expiration:
```
    def getNumDaysLeft(self):
        '''
        Determine the number of days between the curDateTime and the expDateTime.
        curDateTime: current date in mm/dd/yy format.
        expDateTime: option expiration date in mm/dd/yy format.
        :return: number of days between curDateTime and expDateTime.
        '''
        curDateTime = self.getDateTime()
        expDateTime = self.getDTE()
        return (expDateTime - curDateTime).days
```
So `self.getDTE()` which just returns `self.__DTE` should be the expiration date.
But in the unit test `optionTest.py` the `DTE` argument is interpreted as 'days to expiration' (45).
```
classObj = Option('SPY', 250, 'PUT', 0.3, 45)
```
`DTE` is unused in the test.

Based on how the data is read in, in `dataHandler/csvData.py`  DTE is a EST-to-UTC-converted expiration date/time:
```
                local = pytz.timezone('US/Eastern')
                # Convert time zone of data 'US/Eastern' to UTC time.
                # Try and except here to handle two or four digit year format.
                try:
                    DTE = datetime.datetime.strptime(inputData['option_expiration'], "%m/%d/%y")
                except:
                    DTE = datetime.datetime.strptime(inputData['option_expiration'], "%m/%d/%Y")

                DTE = local.localize(DTE, is_dst=None)
                DTE = DTE.astimezone(pytz.utc)
```

So DTE seems a misnomer and would better be called `expDateTime` to avoid confusion.
Similarly in `option.py`: `getDTE()` would be better named `getExpDateTime()`

Note that for the strangle strategy the code actually works since result from `option.getDTE()` is interpreted as `expDateTime` in the arguments to `hasMinimumDTE`, and `self.getMinimumDTE` actually returns a 'days to expiration' within this method:

```
if not self.getMinimumDTE() == None:
                    # we have a min DTE requirement -> does this option meet min DTE requirement?
                    if not self.hasMinimumDTE(option.getDateTime(), option.getDTE()):
                        continue
```
```
  def hasMinimumDTE(self, curDateTime, expDateTime):
      """"
      Determine if the current expiration date of the option is >= self.minimumDTE days from the current date.
      :param curDateTime: current date in mm/dd/yy format.
      :param expDateTime: option expiration date in mm/dd/yy format.
      :return: True if difference between current date and dateTime is >= self.minimumDTE; else False.
      """
      return (expDateTime - curDateTime).days >= self.getMinimumDTE()
```

**Comment by sirnfs** [comment]
Thanks for pointing these out. They should be fixed by the refactor. At the moment, only monthly expirations are supported, but other expirations can easily be added.
